name: grade-school

dependencies:
  - base

library:
  exposed-modules: School
  source-dirs: src
  dependencies:
    - containers
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - grade-school
      - hspec
